project:
  type: book

lang: en-US

book:
  title: "Reading Genomes: A Companion to Bioinformatics and Genome Analysis"
  author: "Laurie Stevison"
  chapters:
    - part: "Companion Chapters"
      chapters:
        - index.qmd
        - ch01-reading-genomes.qmd
        - ch02-sequencing-tech.qmd
        - ch03-formats-qc-design.qmd
        - ch04-browsers-databases.qmd
        - ch05-seq-alignment.qmd
        - ch06-genome-align-assembly.qmd
        - ch07-project-mgmt.qmd
        - ch08-alt-workflows.qmd
        - ch09-hmms.qmd
        - ch10-variant-calling.qmd
        - ch11-grants-funding.qmd
        - ch12-popgen.qmd
        - ch13-motifs.qmd        
        - ch14-where-next.qmd
    - part: "Lab Manual"
      chapters:
        - Lab01.qmd
        - Lab02.qmd
        - Lab03.qmd
        - Lab04.qmd
        - Lab05.qmd
        - Lab06.qmd
        - Lab07.qmd
        - Lab08.qmd
        - Lab09.qmd
        - Lab10.qmd
  appendices:
    - part: "Appendices"
      chapters:
        - appendixA.qmd
        - appendixB.qmd
        - appendixC.qmd  

format:
  html:
    colorlinks: true
    theme: default
    highlight-style: a11y
    toc: true
    number-sections: true
    csl: nature.csl
    axe: true
    include-before-body: skip-nav.html
    toc-title: "Table of Contents"
    anchor-sections: true
    smooth-scroll: true
    css: accessibility.css
  pdf:    
    toc: true
    number-sections: true
    cite-method: biblatex
    biblatexoptions:
      - style=apa
      - backend=biber
      - refsection=chapter
    include-in-header:
      text: |
        \usepackage{hyperref}