<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; File Formats and Quality Control in Genome Workflows – Reading Genomes: A Companion to Bioinformatics and Genome Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ch04-browsers-databases.html" rel="next">
<link href="./ch02-sequencing-tech.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-975e726794ce811e14261b5ab5acfd7c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/quarto-axe/axe-check.js" type="module"></script>
<script id="quarto-axe-checker-options" type="text/plain">dHJ1ZQ==</script>
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-24950670649d35549c6a1355d7402e2b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="accessibility.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./index.html">Companion Chapters</a></li><li class="breadcrumb-item"><a href="./ch03-formats-qc-design.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">File Formats and Quality Control in Genome Workflows</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Reading Genomes: A Companion to Bioinformatics and Genome Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Companion Chapters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch01-reading-genomes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Reading Genomes: What Bioinformatics Is For</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch02-sequencing-tech.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Sequencing Technologies and Data Formats</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch03-formats-qc-design.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">File Formats and Quality Control in Genome Workflows</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch04-browsers-databases.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Genome Databases and Browsers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch05-seq-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sequence Alignment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch06-genome-align-assembly.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Genome Alignment and Genome Assembly</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch07-project-mgmt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Project Management and Writing Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch08-alt-workflows.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Alternative Post‑Alignment Workflows</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch09-hmms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hidden Markov Models in Biology</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch10-variant-calling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Variant Calling and Filtering with GATK</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch11-grants-funding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Grant Funding and the Scientific Enterprise</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch12-popgen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Population Genomics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch13-motifs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Sequence Motif Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch14-where-next.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Where to Go Next: Synthesis, Emerging Frontiers, and Lifelong Learning in Genomics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Lab Manual</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lab01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Lab01: Find and describe a Genome Analysis Paper</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lab02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Lab02: Design a Genome Project</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lab03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Lab03: Genome Browsers and Databases</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lab04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Lab04: Genome Sequence Indexing and Alignment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lab05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Lab05: BLAST on the Command Line</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lab06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Lab06: HMMs in Predicting Gene Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lab07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Lab07: Variant Calling via GATK Best Practices</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lab08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Lab08: Beyond GATK – Benchmarking Variant Calling Pipelines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lab09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Lab09: IGV Genome Visualization Lab Activity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lab10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Lab 10: Population Genomics using the 1000 Genomes Dataset</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendixA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Appendix: How to Read Scientific Literature</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendixB.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Appendix: Semester Research Project</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendixC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Appendix: Yeast Experimental Evolution Dataset</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendixD.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Appendix: Resources for Future Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of Contents</h2>
   
  <ul>
  <li><a href="#sec-ch3" id="toc-sec-ch3" class="nav-link active" data-scroll-target="#sec-ch3"><span class="header-section-number">3.1</span> Introduction to Genome File Formats</a>
  <ul class="collapse">
  <li><a href="#common-genome-analysis-file-formats" id="toc-common-genome-analysis-file-formats" class="nav-link" data-scroll-target="#common-genome-analysis-file-formats"><span class="header-section-number">3.1.1</span> Common Genome Analysis File Formats</a></li>
  </ul></li>
  <li><a href="#fasta-the-foundation-of-sequence-data" id="toc-fasta-the-foundation-of-sequence-data" class="nav-link" data-scroll-target="#fasta-the-foundation-of-sequence-data"><span class="header-section-number">3.2</span> FASTA: The Foundation of Sequence Data</a>
  <ul class="collapse">
  <li><a href="#fasta-file-structure" id="toc-fasta-file-structure" class="nav-link" data-scroll-target="#fasta-file-structure"><span class="header-section-number">3.2.1</span> FASTA File Structure</a></li>
  <li><a href="#from-individual-sequences-to-genomic-scale" id="toc-from-individual-sequences-to-genomic-scale" class="nav-link" data-scroll-target="#from-individual-sequences-to-genomic-scale"><span class="header-section-number">3.2.2</span> From Individual Sequences to Genomic Scale</a></li>
  </ul></li>
  <li><a href="#fastq-raw-sequencing-reads" id="toc-fastq-raw-sequencing-reads" class="nav-link" data-scroll-target="#fastq-raw-sequencing-reads"><span class="header-section-number">3.3</span> FASTQ: Raw Sequencing Reads</a>
  <ul class="collapse">
  <li><a href="#fastq-header-format" id="toc-fastq-header-format" class="nav-link" data-scroll-target="#fastq-header-format"><span class="header-section-number">3.3.1</span> FASTQ Header Format</a></li>
  <li><a href="#phred-quality-scores" id="toc-phred-quality-scores" class="nav-link" data-scroll-target="#phred-quality-scores"><span class="header-section-number">3.3.2</span> Phred Quality Scores</a></li>
  </ul></li>
  <li><a href="#quality-control-fastqc-interpretation" id="toc-quality-control-fastqc-interpretation" class="nav-link" data-scroll-target="#quality-control-fastqc-interpretation"><span class="header-section-number">3.4</span> Quality Control: FastQC Interpretation</a></li>
  <li><a href="#sambam-aligned-reads" id="toc-sambam-aligned-reads" class="nav-link" data-scroll-target="#sambam-aligned-reads"><span class="header-section-number">3.5</span> SAM/BAM: Aligned Reads</a>
  <ul class="collapse">
  <li><a href="#the-sambam-format-and-samtools" id="toc-the-sambam-format-and-samtools" class="nav-link" data-scroll-target="#the-sambam-format-and-samtools"><span class="header-section-number">3.5.1</span> The SAM/baM Format and SAMtools</a></li>
  </ul></li>
  <li><a href="#vcf-variant-call-format" id="toc-vcf-variant-call-format" class="nav-link" data-scroll-target="#vcf-variant-call-format"><span class="header-section-number">3.6</span> VCF: Variant Call Format</a>
  <ul class="collapse">
  <li><a href="#vcf-file-format-details" id="toc-vcf-file-format-details" class="nav-link" data-scroll-target="#vcf-file-format-details"><span class="header-section-number">3.6.1</span> VCF File Format Details</a></li>
  <li><a href="#example-vcf-data" id="toc-example-vcf-data" class="nav-link" data-scroll-target="#example-vcf-data"><span class="header-section-number">3.6.2</span> Example VCF Data</a></li>
  <li><a href="#quality-metrics" id="toc-quality-metrics" class="nav-link" data-scroll-target="#quality-metrics"><span class="header-section-number">3.6.3</span> Quality Metrics</a></li>
  </ul></li>
  <li><a href="#variant-types-beyond-snps" id="toc-variant-types-beyond-snps" class="nav-link" data-scroll-target="#variant-types-beyond-snps"><span class="header-section-number">3.7</span> Variant Types Beyond SNPs</a>
  <ul class="collapse">
  <li><a href="#variant-types-in-vcf-files" id="toc-variant-types-in-vcf-files" class="nav-link" data-scroll-target="#variant-types-in-vcf-files"><span class="header-section-number">3.7.1</span> Variant Types in VCF Files</a></li>
  </ul></li>
  <li><a href="#bed-file-format-and-bedtools" id="toc-bed-file-format-and-bedtools" class="nav-link" data-scroll-target="#bed-file-format-and-bedtools"><span class="header-section-number">3.8</span> BED file format and BEDtools</a>
  <ul class="collapse">
  <li><a href="#bed-file-structure" id="toc-bed-file-structure" class="nav-link" data-scroll-target="#bed-file-structure"><span class="header-section-number">3.8.1</span> BED File Structure</a></li>
  <li><a href="#example-bed-files" id="toc-example-bed-files" class="nav-link" data-scroll-target="#example-bed-files"><span class="header-section-number">3.8.2</span> Example BED Files</a></li>
  <li><a href="#working-with-bed-files-bedtools" id="toc-working-with-bed-files-bedtools" class="nav-link" data-scroll-target="#working-with-bed-files-bedtools"><span class="header-section-number">3.8.3</span> Working with BED Files: BEDTools</a></li>
  <li><a href="#bed-format-in-other-tools" id="toc-bed-format-in-other-tools" class="nav-link" data-scroll-target="#bed-format-in-other-tools"><span class="header-section-number">3.8.4</span> BED Format in Other Tools</a></li>
  <li><a href="#connection-to-genome-browsers" id="toc-connection-to-genome-browsers" class="nav-link" data-scroll-target="#connection-to-genome-browsers"><span class="header-section-number">3.8.5</span> Connection to Genome Browsers</a></li>
  </ul></li>
  <li><a href="#practice-problemsets" id="toc-practice-problemsets" class="nav-link" data-scroll-target="#practice-problemsets"><span class="header-section-number">3.9</span> Practice Problem‑sets</a></li>
  <li><a href="#reflection-questions" id="toc-reflection-questions" class="nav-link" data-scroll-target="#reflection-questions"><span class="header-section-number">3.10</span> Reflection Questions</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">3.11</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<a href="#quarto-content" class="skip-nav">Skip to main content</a>
<style>
.skip-nav {
  position: absolute;
  left: -10000px;
  top: auto;
  width: 1px;
  height: 1px;
  overflow: hidden;
}
.skip-nav:focus {
  position: fixed;
  top: 0;
  left: 0;
  width: auto;
  height: auto;
  padding: 8px;
  background: #000;
  color: #fff;
  text-decoration: none;
  z-index: 9999;
}
</style>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./index.html">Companion Chapters</a></li><li class="breadcrumb-item"><a href="./ch03-formats-qc-design.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">File Formats and Quality Control in Genome Workflows</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">File Formats and Quality Control in Genome Workflows</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-ch3" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-ch3"><span class="header-section-number">3.1</span> Introduction to Genome File Formats</h2>
<p>Next-generation sequencing (NGS) generates massive datasets that flow through standardized workflows from raw reads to biological insights<span class="citation" data-cites="pevsner2015"><sup><a href="#ref-pevsner2015" role="doc-biblioref">1</a></sup></span>. Understanding file formats is essential for experimental design, as each format encodes metadata critical for downstream analysis decisions.</p>
<p>Figure <a href="#fig-ngs-workflow" class="quarto-xref">Figure&nbsp;<span>3.1</span></a> shows the standard NGS pipeline, where FASTQ files capture raw sequencing data, SAM/BAM store alignments, and VCF summarizes variants.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Figure 3.1 – NGS Workflow
</div>
</div>
<div class="callout-body-container callout-body">
<div id="fig-ngs-workflow" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Flowchart of four NGS workflow steps: sequencing, alignment, variant calling, and visualization.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ngs-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Fig_3_1_ngs_workflow.png" class="img-fluid figure-img" style="width:25.0%" alt="Flowchart of four NGS workflow steps: sequencing, alignment, variant calling, and visualization.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ngs-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1: Standard NGS workflow
</figcaption>
</figure>
</div>
<p>Workflow for next-generation sequence experiments: from experimental design to data analysis with the standard file formats for each step. Each file format is described in depth in this chapter and in the table below. Created with BioRender.com.</p>
</div>
</div>
<p>Additionally, visualizing next-generation sequence data as well as genomic arithmetic can be done using genome viewer softwares, such as Integrated Genome Viewer (IGV), which we will cover later in this course. Another common file format in genomics is the BED format, which can be used with genome views, to perform various genome analyses, and to make custom tracks in genome browsers.</p>
<p>The goal of this chapter is to familiarize you with these four major file formats, which are reviewed in this chapter:</p>
<section id="common-genome-analysis-file-formats" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="common-genome-analysis-file-formats"><span class="header-section-number">3.1.1</span> Common Genome Analysis File Formats</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Format</th>
<th>Acronym</th>
<th>Description</th>
<th>Primary Toolkit(s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>FASTA</td>
<td>FASTA</td>
<td>Text-based format for representing nucleotide or protein sequences with sequence identifiers</td>
<td>Biopython, BioPerl, seqtk, samtools faidx, EMBOSS</td>
</tr>
<tr class="even">
<td>FASTQ</td>
<td>FASTQ</td>
<td>Extension of FASTA that includes per-base quality scores from sequencing instruments</td>
<td>FastQC, Trimmomatic, cutadapt, seqtk</td>
</tr>
<tr class="odd">
<td>SAM/BAM</td>
<td>Sequence Alignment/Map (Binary)</td>
<td>Stores aligned sequence reads to a reference genome; BAM is compressed binary version</td>
<td>SAMtools, Picard, GATK, sambamba</td>
</tr>
<tr class="even">
<td>VCF/BCF</td>
<td>Variant Call Format (Binary)</td>
<td>Describes genetic variations including SNPs, indels, and structural variants; BCF is binary version</td>
<td>BCFtools, GATK, VCFtools, vcflib, R: VariantAnnotation, vcfR</td>
</tr>
<tr class="odd">
<td>BED</td>
<td>Browser Extensible Data</td>
<td>Tab-delimited format for genomic intervals and annotations (chromosome, start, end)</td>
<td>BEDtools, UCSC tools, pybedtools, R: GenomicRanges, rtracklayer</td>
</tr>
</tbody>
</table>
<section id="additional-common-formats-covered-later" class="level4" data-number="3.1.1.1">
<h4 data-number="3.1.1.1" class="anchored" data-anchor-id="additional-common-formats-covered-later"><span class="header-section-number">3.1.1.1</span> Additional Common Formats covered later</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Format</th>
<th>Acronym</th>
<th>Description</th>
<th>Primary Toolkit(s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GFF/GTF</td>
<td>General Feature Format / Gene Transfer Format</td>
<td>Annotation formats describing genomic features like genes, transcripts, and exons</td>
<td>gffread, bedtools, AGAT</td>
</tr>
<tr class="even">
<td>CRAM</td>
<td>CRAM</td>
<td>Highly compressed alternative to BAM with reference-based compression</td>
<td>SAMtools, htslib</td>
</tr>
<tr class="odd">
<td>bigWig/bigBed</td>
<td>-</td>
<td>Indexed binary formats for dense continuous data (bigWig) and interval data (bigBed)</td>
<td>UCSC tools (bigWigToBedGraph), deepTools</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Lab connections
</div>
</div>
<div class="callout-body-container callout-body">
<p>This chapter’s file formats and QC concepts feed directly into the first two labs:</p>
<ul>
<li><strong><a href="./Lab01.html">Lab 1</a></strong> asks you to identify how published genome analysis papers report assembly metrics and QC, and to relate those choices back to FASTQ, BAM, and VCF concepts.</li>
<li><strong><a href="./Lab02.html">Lab 2</a></strong> asks you to design a genome project that makes concrete decisions about coverage, platforms, and workflows—decisions that will be encoded in FASTQ, BAM, VCF, and BED files.</li>
</ul>
</div>
</div>
</section>
</section>
</section>
<section id="fasta-the-foundation-of-sequence-data" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="fasta-the-foundation-of-sequence-data"><span class="header-section-number">3.2</span> FASTA: The Foundation of Sequence Data</h2>
<p>Last chapter discussed Sanger sequencing and the generation of <a href="https://www.labxchange.org/library/pathway/lx-pathway:ff079975-ac71-418a-ac93-2e14b056f539/items/lb:LabXchange:22c08d85:html:1/58303?t=8c80f5c3-6a6b-49cf-9d3a-87f332b26c42"><strong>chromatograms</strong></a>—the colorful trace files produced by these sequencing instruments. While chromatograms preserve valuable quality information about individual sequencing reactions, they are impractical for computational analysis and database storage. This challenge led to the development of text-based sequence formats that could efficiently represent biological sequences while remaining human-readable and computationally tractable. The most fundamental and enduring of these formats is FASTA.</p>
<p>The FASTA format was developed in <strong>1985</strong> by <strong>William R. Pearson</strong> and <strong>David J. Lipman</strong> at the National Institutes of Health<span class="citation" data-cites="lipman_rapid_1985 pearson_improved_1988"><sup><a href="#ref-lipman_rapid_1985" role="doc-biblioref">2</a>,<a href="#ref-pearson_improved_1988" role="doc-biblioref">3</a></sup></span>. Originally created for their FASTP protein sequence similarity search program, the format was designed to handle the exponentially growing genetic databases of the 1980s when computer memory and processing speed were severely limited. The name “FASTA” stands for “FAST-All,” reflecting the program’s ability to handle both protein (FAST-P) and nucleotide (FAST-N) sequences.</p>
<section id="fasta-file-structure" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="fasta-file-structure"><span class="header-section-number">3.2.1</span> FASTA File Structure</h3>
<p>A FASTA file consists of one or more sequence records, each with two components:</p>
<p><strong>1. Definition line (header):</strong></p>
<ul>
<li>Begins with <code>&gt;</code> character</li>
<li>First word (no spaces) is the <strong>sequence identifier</strong></li>
<li>Remaining text is <strong>optional description</strong></li>
<li>Must be unique within the file</li>
</ul>
<p><strong>2. Sequence data:</strong></p>
<ul>
<li>Uses standard IUPAC single-letter codes</li>
<li>Typically wrapped to 60-80 characters per line (for readability)</li>
<li>Case-insensitive (though lowercase sometimes indicates masked/repeat regions)</li>
<li>Whitespace and numbers are ignored</li>
</ul>
<p>FASTA files store only sequence data, not quality scores. Additionally, compression with <code>gzip</code> is common for large genome FASTA files, and many bioinformatics tools can read compressed FASTA files directly (<code>.fasta.gz</code> or <code>.fa.gz</code>).</p>
</section>
<section id="from-individual-sequences-to-genomic-scale" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="from-individual-sequences-to-genomic-scale"><span class="header-section-number">3.2.2</span> From Individual Sequences to Genomic Scale</h3>
<p>While FASTA files are plain text and viewable in any text editor, specialized tools enhance their utility. In the next chapter on Genome Browsers, we will install <strong>AliView</strong>, a cross-platform tool that can visualize FASTA files along with other sequence formats. AliView is particularly useful for viewing multiple sequence alignments and comparing sequences side-by-side.</p>
<p>The evolution from Sanger sequencing chromatograms to FASTA files to modern high-throughput formats reflects the scaling challenges in genomics. Where a single Sanger reaction produced one chromatogram file (~1 KB) representing ~800 bp of sequence, modern Illumina sequencing produces billions of reads requiring formats like FASTQ (for raw reads) and BAM (for alignments). Yet FASTA remains the standard for reference genomes, gene sequences, and protein databases—a testament to the format’s elegance and utility established nearly 40 years ago.</p>
</section>
</section>
<section id="fastq-raw-sequencing-reads" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="fastq-raw-sequencing-reads"><span class="header-section-number">3.3</span> FASTQ: Raw Sequencing Reads</h2>
<p>When genomic DNA is sequenced, raw image files are typically generated that are used to interpret which nucleotide is called in a given fragment or “read”. For most users, the FASTQ files (rather than the underlying image files) represent the raw reads from which other analyses are performed. Like the FASTA format, the FASTQ format includes a sequence string, consisting of the nucleotide sequence of each read. FASTQ also includes an associated quality score for every base.</p>
<p>FASTQ extends FASTA by adding per-base quality scores, forming the foundation of NGS analysis. Each record spans four lines<span class="citation" data-cites="pevsner2015 cock2010"><sup><a href="#ref-pevsner2015" role="doc-biblioref">1</a>,<a href="#ref-cock2010" role="doc-biblioref">4</a></sup></span>:</p>
<ol type="1">
<li><strong>Header</strong> (<code>@</code>): Encodes rich metadata about sequencing conditions</li>
<li><strong>Sequence</strong>: Raw nucleotides (A/C/G/T/N)</li>
<li><strong>Separator</strong> (<code>+</code>): Optional repeat of header</li>
<li><strong>Quality scores</strong>: ASCII-encoded Phred values</li>
</ol>
<p>Each FASTQ file has records that are in blocks four lines long. The first line, beginning with the @ symbol, identifies the record. It may optionally include information about the sequence length or the machine used for sequencing. The second line has the sequence (in upper case), including the nucleotides G, A, T, C, and (as is the case here in the second position) there may be an N for unknown nucleotide. The third line begins with the + symbol and typically contains just that character (as in this case), or it can have more information. The fourth line includes the quality scores corresponding to every base. Each quality score is assigned a single character, and the entire quality score string must equal the length of the sequence string.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Sample FASTQ entry
</div>
</div>
<div class="callout-body-container callout-body">
<p>A four-line FASTQ entry showing a single read of a genome sequenced sample:</p>
<pre><code>@SRR1693691.1 HWI-ST591:122:D19EFACXX:1:1101:1948:2137 length=75
CTATAGATCGACGCATATGTATTATCTTAAATAGGTTGCAATATATTATTATTTTTTAACATTTATTGCGATGCT
+SRR1693691.1 HWI-ST591:122:D19EFACXX:1:1101:1948:2137 length=75
?@@DFDDFHA&lt;CDHGIGJIHGHJIGIJJGIIIICHGHJJIGIHGHIJHIJGIJJJIIGGGIIGJGIDEDH&lt;?BEE</code></pre>
<p>This represents a single Illumina sequencing read of 75 base pairs. The first line gives the header, the next the sequence, the next repeats the header, and the last line is hte ASCII-encode Phred quality scores for each position.</p>
</div>
</div>
<section id="fastq-header-format" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="fastq-header-format"><span class="header-section-number">3.3.1</span> FASTQ Header Format</h3>
<p>FASTQ headers contain important metadata about each sequencing read and typically uses <strong>colons (<code>:</code>)</strong> as delimiters. However, the exact format has evolved over time as Illumina updated their sequencing platforms. Understanding these variations is important when working with data from different sources so that reads can be paired correctly, quality control tracks flowcell lanes properly, and to ensure tool compatibility. Generally, Illumina headers contain important metadata about the sequencing run, such as instrument, run, flowcell, lane, etc.<span class="citation" data-cites="pevsner2015"><sup><a href="#ref-pevsner2015" role="doc-biblioref">1</a></sup></span>.</p>
<p>For example, imagine the first line of the FastQ file looks something like this:</p>
<p><strong>“@HS2000-306_201:6:1204:19922:79127/1”</strong></p>
<p>This header string is an example of the modern Illumina FASTQ header fields (Casava 1.8+) and reveals the following metadata of the sequencing reads in the corresponding file:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Information in header</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HS2000-306_201</td>
<td>the unique instrument name</td>
</tr>
<tr class="even">
<td>6</td>
<td>flowcell lane</td>
</tr>
<tr class="odd">
<td>1204</td>
<td>tile number within the flowcell lane</td>
</tr>
<tr class="even">
<td>19922</td>
<td>x-coordinate of the cluster within the tile</td>
</tr>
<tr class="odd">
<td>79127</td>
<td>y-coordinate of the cluster within the tile</td>
</tr>
<tr class="even">
<td>1</td>
<td>the member of a pair, 1 or 2 (paired-end)</td>
</tr>
</tbody>
</table>
<p>When data is downloaded from NCBI’s Sequence Read Archive (SRA), or from older Illumina platforms, the header format differs, as you might notice in the example FASTQ entry above.</p>
<p><strong>SRA Format in example above:</strong></p>
<ul>
<li>Begins with <strong>SRA accession number</strong> (e.g., SRR1693691) followed by the original Illumina header</li>
<li>The SRA accession is followed by a period and read number (<code>.1</code> or <code>.2</code> for paired reads) with a space before the instrument name instead of a colon</li>
<li>May include additional metadata like <code>length=75</code> at the end</li>
<li>Original Illumina information preserved after the SRA identifier</li>
<li>Older formats may also include a <strong>flowcell ID</strong> (e.g., D19EFACXX) not present in modern format</li>
</ul>
<p>The specific metadata encoded in the identifier varies by sequencing platform and processing pipeline, but the fundamental purpose remains the same: uniquely identifying each sequencing read and providing traceability to its origin on the sequencer.</p>
</section>
<section id="phred-quality-scores" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="phred-quality-scores"><span class="header-section-number">3.3.2</span> Phred Quality Scores</h3>
<p>PHRED scores were introduced in 1988 by Phil Green and colleagues to describe base quality scores from Sanger sequencing. This definition is used in the Sanger FASTQ format. Characters are stored as ASCII printable characters 33–126 (i.e., with an ASCII offset of 33) so the range of possible quality scores is 0 to 93. These are listed in Figure 9.8. A value of 93 corresponds to a probability of 10^–9.3 that a base call occurred by chance, that is, the read is extremely likely to be correct. At Q30 there is a 1:1000 (i.e., 10–3) error rate, a threshold that is often set as a minimum for high-quality reads.</p>
<p>Quality scores use Phred scale: <span class="math inline">\(Q = -10\log_{10}(P_e)\)</span> where <span class="math inline">\(P_e\)</span> is error probability<span class="citation" data-cites="pevsner2015"><sup><a href="#ref-pevsner2015" role="doc-biblioref">1</a></sup></span>. ASCII encoding adds +33 offset for printable characters:</p>
<div id="tbl-one" class="smaller quarto-float quarto-figure quarto-figure-center anchored" style="overflow-x: auto;">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-one-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.1: <strong>Table 3.1 Phred-to-ASCII Conversion</strong>. FASTQ quality scores use ASCII coding symbols. The table belows shows ASCII symbols (Char columns indicate characters) corresponding to decimal notation 1–127. The characters for 0–31 (which are not used for printing) are shown in grey. Decimal 32 is a space, and subsequent characters (decimal 33–126) are used to represent base quality scores in the Sanger FASTQ format. Because FASTQ files in standard Sanger format use <strong>Phred+33</strong> encoding: you can simply subtract 33 from the ASCII code to recover the Phred quality score, or add 33 to a Phred score to get the printable FASTQ character. For example, if base calls GATC have quality scores of 28, 30, 25, and 31 then the symbols for their quality scores are =?:@. Printable quality values run from ASCII 33 (<code>!</code>) through 126 (<code>~</code>), which corresponds to Phred scores 0 through 93. Adapted from http://www.lookuptables.com. <em>Gray entries are non-printing or separator characters; red entries are printable ASCII symbols used in FASTQ quality encoding.</em>
</figcaption>
<div aria-describedby="tbl-one-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="smaller caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Dec</th>
<th style="text-align: center;">Char</th>
<th style="text-align: right;">Phred+33</th>
<th style="text-align: right;">Dec</th>
<th style="text-align: center;">Char</th>
<th style="text-align: right;">Phred+33</th>
<th style="text-align: right;">Dec</th>
<th style="text-align: center;">Char</th>
<th style="text-align: right;">Phred+33</th>
<th style="text-align: right;">Dec</th>
<th style="text-align: center;">Char</th>
<th style="text-align: right;">Phred+33</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">32</td>
<td style="text-align: center;"><span style="color: #767676;">Space</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">64</td>
<td style="text-align: center;"><span style="color: #c00000;">@</span></td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">96</td>
<td style="text-align: center;"><span style="color: #c00000;">`</span></td>
<td style="text-align: right;">63</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">33</td>
<td style="text-align: center;"><span style="color: #c00000;">!</span></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">65</td>
<td style="text-align: center;"><span style="color: #c00000;">A</span></td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">97</td>
<td style="text-align: center;"><span style="color: #c00000;">a</span></td>
<td style="text-align: right;">64</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">34</td>
<td style="text-align: center;"><span style="color: #c00000;">"</span></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">66</td>
<td style="text-align: center;"><span style="color: #c00000;">B</span></td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">98</td>
<td style="text-align: center;"><span style="color: #c00000;">b</span></td>
<td style="text-align: right;">65</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">35</td>
<td style="text-align: center;"><span style="color: #c00000;">#</span></td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">67</td>
<td style="text-align: center;"><span style="color: #c00000;">C</span></td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">99</td>
<td style="text-align: center;"><span style="color: #c00000;">c</span></td>
<td style="text-align: right;">66</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">36</td>
<td style="text-align: center;"><span style="color: #c00000;">$</span></td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">68</td>
<td style="text-align: center;"><span style="color: #c00000;">D</span></td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">100</td>
<td style="text-align: center;"><span style="color: #c00000;">d</span></td>
<td style="text-align: right;">67</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">37</td>
<td style="text-align: center;"><span style="color: #c00000;">%</span></td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">69</td>
<td style="text-align: center;"><span style="color: #c00000;">E</span></td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">101</td>
<td style="text-align: center;"><span style="color: #c00000;">e</span></td>
<td style="text-align: right;">68</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">38</td>
<td style="text-align: center;"><span style="color: #c00000;">&amp;</span></td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">70</td>
<td style="text-align: center;"><span style="color: #c00000;">F</span></td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">102</td>
<td style="text-align: center;"><span style="color: #c00000;">f</span></td>
<td style="text-align: right;">69</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">39</td>
<td style="text-align: center;"><span style="color: #c00000;">’</span></td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">71</td>
<td style="text-align: center;"><span style="color: #c00000;">G</span></td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">103</td>
<td style="text-align: center;"><span style="color: #c00000;">g</span></td>
<td style="text-align: right;">70</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">40</td>
<td style="text-align: center;"><span style="color: #c00000;">(</span></td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">72</td>
<td style="text-align: center;"><span style="color: #c00000;">H</span></td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">104</td>
<td style="text-align: center;"><span style="color: #c00000;">h</span></td>
<td style="text-align: right;">71</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">41</td>
<td style="text-align: center;"><span style="color: #c00000;">)</span></td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">73</td>
<td style="text-align: center;"><span style="color: #c00000;">I</span></td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">105</td>
<td style="text-align: center;"><span style="color: #c00000;">i</span></td>
<td style="text-align: right;">72</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">42</td>
<td style="text-align: center;"><span style="color: #c00000;">*</span></td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">74</td>
<td style="text-align: center;"><span style="color: #c00000;">J</span></td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">106</td>
<td style="text-align: center;"><span style="color: #c00000;">j</span></td>
<td style="text-align: right;">73</td>
</tr>
<tr class="even">
<td style="text-align: right;">11</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">43</td>
<td style="text-align: center;"><span style="color: #c00000;">+</span></td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">75</td>
<td style="text-align: center;"><span style="color: #c00000;">K</span></td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">107</td>
<td style="text-align: center;"><span style="color: #c00000;">k</span></td>
<td style="text-align: right;">74</td>
</tr>
<tr class="odd">
<td style="text-align: right;">12</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">44</td>
<td style="text-align: center;"><span style="color: #c00000;">,</span></td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">76</td>
<td style="text-align: center;"><span style="color: #c00000;">L</span></td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">108</td>
<td style="text-align: center;"><span style="color: #c00000;">l</span></td>
<td style="text-align: right;">75</td>
</tr>
<tr class="even">
<td style="text-align: right;">13</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">45</td>
<td style="text-align: center;"><span style="color: #c00000;">-</span></td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">77</td>
<td style="text-align: center;"><span style="color: #c00000;">M</span></td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">109</td>
<td style="text-align: center;"><span style="color: #c00000;">m</span></td>
<td style="text-align: right;">76</td>
</tr>
<tr class="odd">
<td style="text-align: right;">14</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">46</td>
<td style="text-align: center;"><span style="color: #c00000;">.</span></td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">78</td>
<td style="text-align: center;"><span style="color: #c00000;">N</span></td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">110</td>
<td style="text-align: center;"><span style="color: #c00000;">n</span></td>
<td style="text-align: right;">77</td>
</tr>
<tr class="even">
<td style="text-align: right;">15</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">47</td>
<td style="text-align: center;"><span style="color: #c00000;">/</span></td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">79</td>
<td style="text-align: center;"><span style="color: #c00000;">O</span></td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">111</td>
<td style="text-align: center;"><span style="color: #c00000;">o</span></td>
<td style="text-align: right;">78</td>
</tr>
<tr class="odd">
<td style="text-align: right;">16</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">48</td>
<td style="text-align: center;"><span style="color: #c00000;">0</span></td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">80</td>
<td style="text-align: center;"><span style="color: #c00000;">P</span></td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">112</td>
<td style="text-align: center;"><span style="color: #c00000;">p</span></td>
<td style="text-align: right;">79</td>
</tr>
<tr class="even">
<td style="text-align: right;">17</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">49</td>
<td style="text-align: center;"><span style="color: #c00000;">1</span></td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">81</td>
<td style="text-align: center;"><span style="color: #c00000;">Q</span></td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">113</td>
<td style="text-align: center;"><span style="color: #c00000;">q</span></td>
<td style="text-align: right;">80</td>
</tr>
<tr class="odd">
<td style="text-align: right;">18</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">50</td>
<td style="text-align: center;"><span style="color: #c00000;">2</span></td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">82</td>
<td style="text-align: center;"><span style="color: #c00000;">R</span></td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">114</td>
<td style="text-align: center;"><span style="color: #c00000;">r</span></td>
<td style="text-align: right;">81</td>
</tr>
<tr class="even">
<td style="text-align: right;">19</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">51</td>
<td style="text-align: center;"><span style="color: #c00000;">3</span></td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">83</td>
<td style="text-align: center;"><span style="color: #c00000;">S</span></td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">115</td>
<td style="text-align: center;"><span style="color: #c00000;">s</span></td>
<td style="text-align: right;">82</td>
</tr>
<tr class="odd">
<td style="text-align: right;">20</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">52</td>
<td style="text-align: center;"><span style="color: #c00000;">4</span></td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">84</td>
<td style="text-align: center;"><span style="color: #c00000;">T</span></td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">116</td>
<td style="text-align: center;"><span style="color: #c00000;">t</span></td>
<td style="text-align: right;">83</td>
</tr>
<tr class="even">
<td style="text-align: right;">21</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">53</td>
<td style="text-align: center;"><span style="color: #c00000;">5</span></td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">85</td>
<td style="text-align: center;"><span style="color: #c00000;">U</span></td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">117</td>
<td style="text-align: center;"><span style="color: #c00000;">u</span></td>
<td style="text-align: right;">84</td>
</tr>
<tr class="odd">
<td style="text-align: right;">22</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">54</td>
<td style="text-align: center;"><span style="color: #c00000;">6</span></td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">86</td>
<td style="text-align: center;"><span style="color: #c00000;">V</span></td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">118</td>
<td style="text-align: center;"><span style="color: #c00000;">v</span></td>
<td style="text-align: right;">85</td>
</tr>
<tr class="even">
<td style="text-align: right;">23</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">55</td>
<td style="text-align: center;"><span style="color: #c00000;">7</span></td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">87</td>
<td style="text-align: center;"><span style="color: #c00000;">W</span></td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">119</td>
<td style="text-align: center;"><span style="color: #c00000;">w</span></td>
<td style="text-align: right;">86</td>
</tr>
<tr class="odd">
<td style="text-align: right;">24</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">56</td>
<td style="text-align: center;"><span style="color: #c00000;">8</span></td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">88</td>
<td style="text-align: center;"><span style="color: #c00000;">X</span></td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">120</td>
<td style="text-align: center;"><span style="color: #c00000;">x</span></td>
<td style="text-align: right;">87</td>
</tr>
<tr class="even">
<td style="text-align: right;">25</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">57</td>
<td style="text-align: center;"><span style="color: #c00000;">9</span></td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">89</td>
<td style="text-align: center;"><span style="color: #c00000;">Y</span></td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">121</td>
<td style="text-align: center;"><span style="color: #c00000;">y</span></td>
<td style="text-align: right;">88</td>
</tr>
<tr class="odd">
<td style="text-align: right;">26</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">58</td>
<td style="text-align: center;"><span style="color: #c00000;">:</span></td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">90</td>
<td style="text-align: center;"><span style="color: #c00000;">Z</span></td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">122</td>
<td style="text-align: center;"><span style="color: #c00000;">z</span></td>
<td style="text-align: right;">89</td>
</tr>
<tr class="even">
<td style="text-align: right;">27</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">59</td>
<td style="text-align: center;"><span style="color: #c00000;">;</span></td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">91</td>
<td style="text-align: center;"><span style="color: #c00000;">left bracket</span></td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">123</td>
<td style="text-align: center;"><span style="color: #c00000;">{</span></td>
<td style="text-align: right;">90</td>
</tr>
<tr class="odd">
<td style="text-align: right;">28</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">60</td>
<td style="text-align: center;"><span style="color: #c00000;">&lt;</span></td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">92</td>
<td style="text-align: center;"><span style="color: #c00000;">\</span></td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">124</td>
<td style="text-align: center;"><span style="color: #c00000;">|</span></td>
<td style="text-align: right;">91</td>
</tr>
<tr class="even">
<td style="text-align: right;">29</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">61</td>
<td style="text-align: center;"><span style="color: #c00000;">=</span></td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">93</td>
<td style="text-align: center;"><span style="color: #c00000;">right bracket</span></td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">125</td>
<td style="text-align: center;"><span style="color: #c00000;">}</span></td>
<td style="text-align: right;">92</td>
</tr>
<tr class="odd">
<td style="text-align: right;">30</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">62</td>
<td style="text-align: center;"><span style="color: #c00000;">&gt;</span></td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">94</td>
<td style="text-align: center;"><span style="color: #c00000;">^</span></td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">126</td>
<td style="text-align: center;"><span style="color: #c00000;">~</span></td>
<td style="text-align: right;">93</td>
</tr>
<tr class="even">
<td style="text-align: right;">31</td>
<td style="text-align: center;"><span style="color: #767676;">Non-printing</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">63</td>
<td style="text-align: center;"><span style="color: #c00000;">?</span></td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">95</td>
<td style="text-align: center;"><span style="color: #c00000;">_</span></td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">127</td>
<td style="text-align: center;"><span style="color: #767676;">DEL</span></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Because genome sequencing has so much data, the cutoffs for Phred scores require added stringency. As is shown in the table below, a typical quality score of 20, which is recommended in most pipelines, ensures a 99% accuracy. Still, this equates to ~100 million sequencing errors in a standard dataset of 10 billion base pairs of DNA. Later, in Chapter 10, we will discuss variant filtering in more detail where additional parameters are used to filter data beyond simply Phred Quality scores of individual base calls.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 34%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Phred Quality Score</th>
<th>Probability of Incorrect Base Call</th>
<th>Base Call Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10</td>
<td>1 in 10</td>
<td>90%</td>
</tr>
<tr class="even">
<td>20</td>
<td>1 in 100</td>
<td>99%</td>
</tr>
<tr class="odd">
<td>30</td>
<td>1 in 1,000</td>
<td>99.9%</td>
</tr>
<tr class="even">
<td>40</td>
<td>1 in 10,000</td>
<td>99.99%</td>
</tr>
<tr class="odd">
<td>50</td>
<td>1 in 100,000</td>
<td>99.999%</td>
</tr>
<tr class="even">
<td>60</td>
<td>1 in 1,000,000</td>
<td>99.9999%</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="quality-control-fastqc-interpretation" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="quality-control-fastqc-interpretation"><span class="header-section-number">3.4</span> Quality Control: FastQC Interpretation</h2>
<p>Several packages are useful to assess the quality of the sequence data. There are many types of sequencing errors:</p>
<ul>
<li><p>Errors typically increase as a function of read length. For example, for Illumina technology, with each increasing cycle it becomes increasingly difficult to differentiate the signal to noise ratio for which nucleotide has been incorporated.</p></li>
<li><p>Errors occur as a function of GC content.</p></li>
<li><p>Errors may occur in homopolymer positions. Both pyrosequencing and Ion Torrent technologies are susceptible to this.</p></li>
</ul>
<p>FastQC software (<span class="citation" data-cites="fastqc"><sup><a href="#ref-fastqc" role="doc-biblioref">5</a></sup></span>) provides quality control statistics. Data are imported from FASTQ files, and are then analyzed for qulality. The output includes the following:</p>
<ul>
<li><p><em>Basic statistics</em>. This includes information such as the range of sequence lengths and the percent GC content.</p></li>
<li><p><em>Per base sequence quality</em>. This shows quality scores (y axis) versus base position (x axis).</p></li>
<li><p><em>Per sequence quality scores</em> shows the number of sequences (y axis) versus mean sequence quality (Phred score; x axis).</p></li>
<li><p><em>Overrepresented sequences</em>. You can copy these sequences and save them to a text file. You can then try BLAT (particularly if you know the species of the overrepresented sequences), BLASTN (to search for matches across species), batch BLAST, or other tools.</p></li>
<li><p><em>k-mer content</em>: this shows data for a series of 5-mers (strings of 5 nucleotides) plotted by relative enrichment (y axis) versus position in read (in base pairs; x axis). The expected 5-mer frequency (determined from the base composition of the entire sequence) can be compared to the observed frequency. k-mer counts may be reduced (e.g., when poor quality reads reduce the counts for duplicated sequences) or enriched (e.g., when 5-mers are overrepresented at particular locations along a read, such as in the vicinity of a tag added to the 5′ end of sequencing reads).</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Figure 3.2 – FastQC Sample Output
</div>
</div>
<div class="callout-body-container callout-body">
<div id="fig-fastqc-plots" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Screenshot of fastqc output for per base sequence Phred quality scores.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fastqc-plots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Fig_3_3_fastqc.png" class="img-fluid figure-img" style="width:75.0%" alt="Screenshot of fastqc output for per base sequence Phred quality scores.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fastqc-plots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.2: FastQC Sample Output
</figcaption>
</figure>
</div>
<p>Sample FastQC output showing a sharp decline in Phred Quality scores along sequence length. This is indicated with a red X in the main panel and indicates a failed quality check. This would typically indicate that trimming of read ends is required to improve overall quality of read data prior to alignment. <a href="https://www.bioinformatics.babraham.ac.uk/projects/fastqc/">Source</a></p>
</div>
</div>
<ul>
<li><strong>Per base sequence quality</strong>: Boxplots by position; expect Q&gt;30 early, decline to Q20+ at ends</li>
<li><strong>Per base sequence content</strong>: Even A/C/G/T; 5’ bias = adapters<br>
</li>
<li><strong>Adapter content</strong>: Rising % indicates contamination</li>
<li><strong>Sequence duplication</strong>: &gt;50% duplicates flags PCR bias</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Coverage Calculation using FastQC or Samtools
</div>
</div>
<div class="callout-body-container callout-body">
<p>Read depth (or depth of coverage) is a basic design consideration. If a library is sequenced more often (e.g., analyzing it on multiple lanes of a flow cell) this will offer greater depth and more statistical power to detect variants. At the same time, obtaining deeper coverage is relatively expensive. For a typical whole-genome sequence using Illumina technology that generates 150 nucleotide paired end reads, coverage of 30× to 50× is obtained, meaning that on average any given base in the genome is covered by 30–50 independent sequencing reads. For whole-exome sequencing (which often spans ∼50 megabases or 1–2% of the genome), depth of coverage is often 100× or more. For targeted sequencing, depth of sequencing ranges from 5× to 30× depending on factors such as the number of samples that are run simultaneously.</p>
<p>The redundancy of coverage c is a function of the number of reads N, the average length of each read L, and the length of the region (e.g., genome G) being sequenced<span class="citation" data-cites="pevsner2015"><sup><a href="#ref-pevsner2015" role="doc-biblioref">1</a></sup></span>:</p>
<p>Coverage = <span class="math inline">\(\frac{N \times L}{G}\)</span> where <span class="math inline">\(G\)</span> = genome size.</p>
<p><strong>Using Samtools depth to calculate coverage</strong>: SAMtools is a library and a software package (Li et al., 2009). We can use it to analyze alignments in the SAM/BAM input, accomplishing various tasks. For example, the tool <strong>samtools depth</strong> is used to give a coverage amount for EVERY position in the genome. Lucky for you it is in a column style format with the following columns:</p>
<ul>
<li>Column 1: ID<br>
</li>
<li>Column 2: Genomic position<br>
</li>
<li>Column 3: No of reads covering that position</li>
</ul>
<p>Using a simple awk command, we can calculate the average coverage using the third column:</p>
<pre class="shell"><code>samtools depth  *bamfile*  |  awk '{sum+=$3} END { print "Average = ",sum/GENOME_SIZE}'</code></pre>
<blockquote class="blockquote">
<p>I also recommend calculating genome size directly as this output does not list sites with zero coverage. While this is less of an issue with your small yeast genomes, for larger genomes it matters. Also note that we have used the masked version of the genome. This simply converts all sites in the genome file that are known to be repetitive (thus difficult to map for short reads) to N’s. These sites in particular are expected to have zero coverage as well.</p>
</blockquote>
<p>You can do this using awk and the file “sacCer3.fa.masked.fai” which has as its second column the total number of bases on each chromosome.</p>
<p><strong>Standard Deviation</strong>: Though not required, you can also calculate <strong>standard deviation</strong> to get an idea of how large of a range in coverage exists across your sample. Try using awk and the formula for standard deviation to accomplish this.</p>
<p><a href="http://standard-deviation.appspot.com/">Standard Deviation Formula</a></p>
<pre class="shell"><code>#hint you will need both the sum and the squared sum:
awk '{sum+=$3; sumsq+=$3*$3} END {print "Stdev = ",sqrt(sumsq/GENOME_SIZE - (sum/GENOME_SIZE)**2)}' depth.output</code></pre>
</div>
</div>
</section>
<section id="sambam-aligned-reads" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="sambam-aligned-reads"><span class="header-section-number">3.5</span> SAM/BAM: Aligned Reads</h2>
<p>The next major step in a basic genome analysis pipeline is alignment, which we will go into a lot of depth in subsequent chapters. When FastQ files are aligned to a reference genome, the output is a SAM (Sequence Alignment/Map) file. This file format is a compressed file that stores read alignments. It can be further compressed into its binoary form BAM<span class="citation" data-cites="pevsner2015"><sup><a href="#ref-pevsner2015" role="doc-biblioref">1</a></sup></span>. Finally, an even more compressed version is a CRAM (Compressed Reference-oriented Alignment Map) file which was introduced in 2011. CRAM is a compressed columnar file format for storing biological sequences aligned to a reference sequence. For the purposes of this chpater, we will focus on the SAM format. BAM files cannot be directly viewed due to their binary nature.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Lab connections
</div>
</div>
<div class="callout-body-container callout-body">
<p>In <strong><a href="./Lab04.html">Lab 4</a></strong> you will provide a practical opportunity to have hands-on experience working with raw fastq files on the Alabama Super Computer. You will also experience moving between these formats as you generate a bam alignment. You will also index a fasta formatted genome file.</p>
<p>This upcoming lab will also allow you to use popular bioinformatics tools to both generate these types of files and perform standard quality control analysis. You will also first encounter the yeast genomics dataset we will be using throughout the semester and be able to practice interpreting QC outputs for a real dataset<span class="citation" data-cites="burke_standing_2014"><sup><a href="#ref-burke_standing_2014" role="doc-biblioref">6</a></sup></span>. See <a href="./appendixC.html">Appendix C</a> for more detail.</p>
</div>
</div>
<section id="the-sambam-format-and-samtools" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="the-sambam-format-and-samtools"><span class="header-section-number">3.5.1</span> The SAM/baM Format and SAMtools</h3>
<p>The SAM (sequence alignment/map) format is commonly used to store next-generation sequence alignments. SAM files can be easily converted to the BAM (binary alignment/map) format. BAM is a binary representation of SAM, compressed by the BGZF library, and contains the same information as the SAM file. Because they are easily interchangeable, we may refer to the SAM/BAM format. This format is very popular, with many datasets available in repositories (such as the Sequence Read Archive at NCBI, the 1000 Genomes Project, and the Cancer Genome Atlas).</p>
<p>The SAM format includes a header section (having lines beginning with the character @) and an alignment section. The file is tab-delimited, and there are 11 mandatory fields (Table 9.4) which we examine in our autism panel (Fig. 9.13). We use the samtools view command to display the first of over a million rows (each row corresponding to a read that has been aligned to a reference genome). Twelve fields are shown, including the sequence (beginning AATCT…) followed by the corresponding quality scores. The CIGAR string refers to a notation system for variants. Here string “148M2S” shows 148 matches and 2 soft-clipped (unaligned) bases. Standard CIGAR operations are M (match), I (insertion), and D (deletion). Extended CIGAR options are N (skipped bases on reference), S (soft clipping), H (hard clipping), and P (padding). SAMtools is a library and a software package (Li et al., 2009). We can use it to analyze alignments in the SAM/BAM input, accomplishing the following tasks:</p>
<ul>
<li>convert from other alignment formats, or between SAM and BAM formats;</li>
<li>sort and merge alignments;</li>
<li>index alignments (once sorted, BAM file can be indexed generating a BAI file used in downstream analyses);</li>
<li>view alignments in the pileup format (as shown below with the samtools view command);</li>
<li>remove PCR duplicates (this procedure, called duplicate marking or “dedupping,” removes reads that are redundant); and</li>
<li>call two classes of variants: single-nucleotide polymorphisms (SNPs) and small indels.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Sample BAM File
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Using SAMtools to view sequence reads from a BAM file at genomic coordinates of interest. By using the samtools tview command you enable a genome-wide view of the reads. Using commands accessed via a help menu, you can view the same reads colored by (a) base quality or (b) mapping quality. The read depth is relatively low to the left side. The quality scores are colored blue (for 0–9), green (10–19), yellow (20–29), or white (≥30). Underlining represents secondary or orphan reads. This viewer is useful to quickly assess the quality at genomic loci of interest, such as positions having single-nucleotide variants.</p>
<div id="fig-sam" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Screenshot of BAM file using samtools tview in terminal.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Fig_3.4_SAMtools_tview.png" class="img-fluid figure-img" style="width:75.0%" alt="Screenshot of BAM file using samtools tview in terminal.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.3: Samtools tview
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>While it is not typical to view BAM files natively, it is helpful to review the anatomay of a sam file and the various ways to view this file format using the bioinformatics software <code>samtools</code>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Table 3.1 – Mandatory Fields in a SAM/BAM Alignment Record
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<caption>The 11 mandatory fields present in every alignment record of a SAM or BAM file, in column order. A SAM file consists of an optional header section (lines beginning with <code>@</code>) followed by one tab-delimited alignment record per read. The binary BAM format stores identical information in compressed form. A typical alignment file for a whole-genome sequencing experiment contains tens to hundreds of millions of records. The command <code>samtools view</code> can be used to view a Sam/Bam file. The drop down menu above shows a sample output of <code>samtools tview</code> on the yeast genome sample. Source: SAM Format Specification<span class="citation" data-cites="Li2009SAMtools"><sup><a href="#ref-Li2009SAMtools" role="doc-biblioref">7</a></sup></span>.</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 19%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Col</th>
<th style="text-align: left;">Field</th>
<th style="text-align: center;">Type</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;">QNAME</td>
<td style="text-align: center;">String</td>
<td style="text-align: left;">Query template name — the read identifier from the sequencer</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;">FLAG</td>
<td style="text-align: center;">Int</td>
<td style="text-align: left;">Bitwise flag encoding alignment properties (paired, reverse strand, unmapped, etc.)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;">RNAME</td>
<td style="text-align: center;">String</td>
<td style="text-align: left;">Reference sequence name (chromosome or contig) where the read aligned</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left;">POS</td>
<td style="text-align: center;">Int</td>
<td style="text-align: left;">1-based leftmost mapping position on the reference</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: left;">MAPQ</td>
<td style="text-align: center;">Int</td>
<td style="text-align: left;">Mapping quality — phred-scaled probability that the alignment position is wrong</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: left;">CIGAR</td>
<td style="text-align: center;">String</td>
<td style="text-align: left;">CIGAR string encoding match, insertion, deletion, and soft-clip operations</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: left;">RNEXT</td>
<td style="text-align: center;">String</td>
<td style="text-align: left;">Reference name of the mate/next read in a paired-end pair (<code>=</code> if same chromosome)</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: left;">PNEXT</td>
<td style="text-align: center;">Int</td>
<td style="text-align: left;">Position of the mate/next read</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td style="text-align: left;">TLEN</td>
<td style="text-align: center;">Int</td>
<td style="text-align: left;">Observed template length (insert size); negative for the reverse-strand read of a pair</td>
</tr>
<tr class="even">
<td style="text-align: center;">10</td>
<td style="text-align: left;">SEQ</td>
<td style="text-align: center;">String</td>
<td style="text-align: left;">Segment sequence of the read (forward strand as aligned)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">11</td>
<td style="text-align: left;">QUAL</td>
<td style="text-align: center;">String</td>
<td style="text-align: left;">ASCII-encoded Phred base quality scores (Phred+33 offset)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The bioinformatics tool <a href="https://www.htslib.org/">SAMtools</a> is a suite of programs for interacting with high-throughput sequencing data<span class="citation" data-cites="danecek_twelve_2021"><sup><a href="#ref-danecek_twelve_2021" role="doc-biblioref">8</a></sup></span>. It consists of three separate repositories:</p>
<ul>
<li>Samtools: Reading/writing/editing/indexing/viewing SAM/BAM/CRAM format</li>
<li>BCFtools: Reading/writing BCF2/VCF/gVCF files and calling/filtering/summarising SNP and short indel sequence variants</li>
<li>HTSlib: A C library for reading/writing high-throughput sequencing data</li>
</ul>
<p>Samtools and BCFtools both use HTSlib internally, but these source packages contain their own copies of htslib so they can be built independently.</p>
<p>These can be used on the HPC which we will do in labs this semester. But you can also install these locally. On a Mac, you may use the package manager <a href="https://brew.sh/">HomeBrew</a> to install <code>samtools</code>. If you are on Windows, first install WSL (Windows Subsystem for Linux) to get a full Linux environment. Then, the easiest approach would be to use a pacakge manager like <code>conda</code> which will also handle dependencies automatically.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Verification of Sam/Bam files using Samtools
</div>
</div>
<div class="callout-body-container callout-body">
<p>Another SAMtools tool, the <strong>samtools flagstat</strong> program is a very useful way to analyze a bam file. From samtools manual it describes flagstat’s function as:</p>
<blockquote class="blockquote">
<p>Does a full pass through the input file to calculate and print statistics to stdout. Provides counts for each of 13 categories based primarily on bit flags in the FLAG field. Each category in the output is broken down into QC pass and QC fail, which is presented as “#PASS + #FAIL” followed by a description of the category. The first row of output gives the total number of reads that are QC pass and fail (according to flag bit 0x200). For example: 122 + 28 in total (QC-passed reads + QC-failed reads) Which would indicate that there are a total of 150 reads in the input file, 122 of which are marked as QC pass and 28 of which are marked as “not passing quality controls”</p>
</blockquote>
<p>Sample output file from running flagstat on a bam file:</p>
<pre class="shell"><code>20968800 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 duplicates
20968800 + 0 mapped (100.00%:nan%)
20968800 + 0 paired in sequencing
11431237 + 0 read1
9537563 + 0 read2
71098 + 0 properly paired (0.34%:nan%)
6633306 + 0 with itself and mate mapped
14335494 + 0 singletons (68.37%:nan%)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ&gt;=5)</code></pre>
</div>
</div>
</section>
</section>
<section id="vcf-variant-call-format" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="vcf-variant-call-format"><span class="header-section-number">3.6</span> VCF: Variant Call Format</h2>
<p>Once FASTQ files from your sample have been aligned to a reference genome, it may be assumed that variants (both single-nucleotide variants and indels) can be called by inspecting the alignment and tabulating the differences. The problem with this approach is that many sources of errors occur in the process of sequencing and performing alignment: bias may occur in how libraries are prepared and amplified; sequencing technologies all have associated error rates; and mapping has error rates.</p>
<p>VCF tabulates variants post-alignment (GATK/SAMtools)<span class="citation" data-cites="pevsner2015 danecek_variant_2011"><sup><a href="#ref-pevsner2015" role="doc-biblioref">1</a>,<a href="#ref-danecek_variant_2011" role="doc-biblioref">9</a></sup></span>.The VCF format was developed under the 1000 Genomes Project and is currently maintained by the Global Alliance for Genomics &amp; Health (GA4GH). For practical guidance on working with VCF files using BCFtools, see<span class="citation" data-cites="learning_vcf"><sup><a href="#ref-learning_vcf" role="doc-biblioref">10</a></sup></span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Lab connections
</div>
</div>
<div class="callout-body-container callout-body">
<p>In <strong><a href="./Lab07.html">Lab 7</a></strong> you will have an opportunity to continue your practical exposure to these file formats as you take the next step in your genome analysis of the yeast genomics dataset. On the Alabama Super Computer, you will get hands-on experience using GATK to call variants from the BAM file you generate in <strong><a href="./Lab04.html">Lab 4</a></strong> creating a VCF file.</p>
<p>This later lab will also guide you in filtering and evaluating variants for quality. You can refer back to this chapter whenever you encounter new datasets or need to interpret QC plots and file structures in labs.</p>
</div>
</div>
<section id="vcf-file-format-details" class="level3" data-number="3.6.1">
<h3 data-number="3.6.1" class="anchored" data-anchor-id="vcf-file-format-details"><span class="header-section-number">3.6.1</span> VCF File Format Details</h3>
<p>A VCF file consists of:</p>
<ul>
<li><strong>Meta-information lines</strong> (starting with <code>##</code>) that define file format, reference genome, and field descriptions</li>
<li><strong>Header line</strong> (starting with <code>#CHROM</code>) that names the columns</li>
<li><strong>Data lines</strong> containing variant information</li>
</ul>
<p><strong>9 mandatory columns</strong> + sample columns:</p>
<div class="cell">
<div id="tbl-vcf-columns" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-vcf-columns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.2: VCF column definitions (Pevsner Table 9.6).
</figcaption>
<div aria-describedby="tbl-vcf-columns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Column</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CHROM</td>
<td style="text-align: left;">Chromosome</td>
</tr>
<tr class="even">
<td style="text-align: left;">POS</td>
<td style="text-align: left;">1-based variant start position</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ID</td>
<td style="text-align: left;">dbSNP rsID or other identifier</td>
</tr>
<tr class="even">
<td style="text-align: left;">REF</td>
<td style="text-align: left;">Reference allele</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ALT</td>
<td style="text-align: left;">Alternate allele(s), comma-separated</td>
</tr>
<tr class="even">
<td style="text-align: left;">QUAL</td>
<td style="text-align: left;">Phred-scaled quality score</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FILTER</td>
<td style="text-align: left;">PASS if passes filters, or filter names</td>
</tr>
<tr class="even">
<td style="text-align: left;">INFO</td>
<td style="text-align: left;">Semicolon-separated annotation fields</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FORMAT</td>
<td style="text-align: left;">Colon-separated format of sample fields</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Genotype encoding</strong>:</p>
<ul>
<li><code>0/0</code> = homozygous reference</li>
<li><code>0/1</code> = heterozygous</li>
<li><code>1/1</code> = homozygous alternate</li>
<li><code>1/2</code> = heterozygous with two different alternate alleles</li>
</ul>
</section>
<section id="example-vcf-data" class="level3" data-number="3.6.2">
<h3 data-number="3.6.2" class="anchored" data-anchor-id="example-vcf-data"><span class="header-section-number">3.6.2</span> Example VCF Data</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Sample VCF File
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Below is an example VCF file showing single nucleotide variants (SNVs) from chromosome I of a yeast genome:</p>
<pre><code>##fileformat=VCFv4.2
##ALT=&lt;ID=NON_REF,Description="Represents any possible alternative allele at this location"&gt;
##FILTER=&lt;ID=LowQual,Description="Low quality"&gt;
##FORMAT=&lt;ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles"&gt;
##FORMAT=&lt;ID=DP,Number=1,Type=Integer,Description="Approximate read depth"&gt;
##FORMAT=&lt;ID=GQ,Number=1,Type=Integer,Description="Genotype Quality"&gt;
##FORMAT=&lt;ID=GT,Number=1,Type=String,Description="Genotype"&gt;
##FORMAT=&lt;ID=PL,Number=G,Type=Integer,Description="Normalized Phred-scaled likelihoods"&gt;
##INFO=&lt;ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes"&gt;
##INFO=&lt;ID=AF,Number=A,Type=Float,Description="Allele Frequency"&gt;
##INFO=&lt;ID=AN,Number=1,Type=Integer,Description="Total number of alleles"&gt;
##INFO=&lt;ID=DP,Number=1,Type=Integer,Description="Approximate read depth"&gt;
##INFO=&lt;ID=MQ,Number=1,Type=Float,Description="RMS Mapping Quality"&gt;
##INFO=&lt;ID=QD,Number=1,Type=Float,Description="Variant Confidence/Quality by Depth"&gt;
##contig=&lt;ID=chrI,length=230218&gt;
##source=HaplotypeCaller
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMN03152093
chrI    136     .       G       A       812.01  .       AC=1;AF=1.00;AN=1;DP=25;MQ=46.32;QD=32.48     GT:AD:DP:GQ:PL  1:4,21:25:99:822,0
chrI    349     .       C       T       191.01  .       AC=1;AF=1.00;AN=1;DP=17;MQ=46.06;QD=11.24     GT:AD:DP:GQ:PL  1:6,11:17:99:201,0
chrI    457     .       CA      C       194.01  .       AC=1;AF=1.00;AN=1;DP=12;MQ=39.48;QD=32.33     GT:AD:DP:GQ:PL  1:0,6:10:99:204,0
chrI    610     .       G       A       80.01   .       AC=1;AF=1.00;AN=1;DP=2;MQ=33.14;QD=28.73      GT:AD:DP:GQ:PL  1:0,2:2:90:90,0</code></pre>
<p><strong>Key observations:</strong></p>
<ul>
<li>Position 136: G→A SNV with high quality (QUAL=812) and good mapping quality (MQ=46.32)</li>
<li>Position 457: 2bp deletion (CA→C) representing an indel</li>
<li>INFO field QD (Quality by Depth) helps assess variant confidence relative to coverage</li>
<li>FORMAT GT field shows genotype: <code>1</code> indicates homozygous alternate (haploid sample)</li>
</ul>
</div>
</div>
</div>
</section>
<section id="quality-metrics" class="level3" data-number="3.6.3">
<h3 data-number="3.6.3" class="anchored" data-anchor-id="quality-metrics"><span class="header-section-number">3.6.3</span> Quality Metrics</h3>
<p>Understanding VCF quality fields is crucial for variant filtering:</p>
<ul>
<li><strong>QUAL</strong>: Phred-scaled probability that the variant call is incorrect (higher is better)</li>
<li><strong>QD (Quality by Depth)</strong>: QUAL/DP ratio; helps identify false positives from low-coverage regions</li>
<li><strong>MQ (Mapping Quality)</strong>: Root mean square of mapping quality scores; indicates alignment confidence</li>
<li><strong>DP (Depth)</strong>: Number of reads covering the position</li>
<li><strong>GQ (Genotype Quality)</strong>: Confidence in the assigned genotype</li>
</ul>
<p>These metrics are typically used together to filter high-confidence variants from sequencing artifacts, which we will get into in depth later in the course as part of Chapter 10.</p>
</section>
</section>
<section id="variant-types-beyond-snps" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="variant-types-beyond-snps"><span class="header-section-number">3.7</span> Variant Types Beyond SNPs</h2>
<p>The outline of a genome analysis workflow presented in Figure 9.6 is relatively simplistic. We will use that workflow to gain experience with basic data manipulation. A state-of-the-art workflow, used by many experts, is the Genome Analysis Toolkit (GATK;<span class="citation" data-cites="mckenna_genome_2010 depristo_framework_2011"><sup><a href="#ref-mckenna_genome_2010" role="doc-biblioref">11</a>,<a href="#ref-depristo_framework_2011" role="doc-biblioref">12</a></sup></span>). We show the GATK workflow in Figure 9.7, and explain why its approaches are crucial to sensitive, specific analyses of genome sequences.</p>
<p>The basic GATK workflow is used for variant discovery with the goal output being a VCF. But in addition to SNPs, GATK can be used to call other types of genomic variants. Specifically, GATK can be used to identify indels and other structural variants<span class="citation" data-cites="pevsner2015"><sup><a href="#ref-pevsner2015" role="doc-biblioref">1</a></sup></span>:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Figure 3.4 – GATK Workflow
</div>
</div>
<div class="callout-body-container callout-body">
<div id="fig-gatk-workflow" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Flowchart showing the GATK best practices workflow.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gatk-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Fig_3_4_gatk.jpg" class="img-fluid figure-img" style="width:75.0%" alt="Flowchart showing the GATK best practices workflow.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gatk-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.4: GATK pipeline: raw reads → analysis-ready BAM → VCF.)
</figcaption>
</figure>
</div>
<p><strong>GATK Best Practices</strong> (Figure @ref(fig:gatk-workflow)) is the best genome workflow for model organisms, and for modern human genomics. However, it may not be suitable for calling variants in non-model systems, which will be covered later in the course<span class="citation" data-cites="mckenna_genome_2010 depristo_framework_2011"><sup><a href="#ref-mckenna_genome_2010" role="doc-biblioref">11</a>,<a href="#ref-depristo_framework_2011" role="doc-biblioref">12</a></sup></span>. Each step in the GATK pipeline reduces the amount of data in a genome analysis, the goal is to improve the overall quality of the results that are filtered along the way. For example, we may expect to see up to 50% of the data is removed during a standard workflow from raw FastQ file to a VCF. This does not mean that your data are of poor quality of that your experimental design was flawed, but only that your resulting variants have been stringently filtered to be of the highest confidence. Adapted from Broad Institute GATK tutorial figures; reproduced for educational use.</p>
</div>
</div>
<section id="variant-types-in-vcf-files" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="variant-types-in-vcf-files"><span class="header-section-number">3.7.1</span> Variant Types in VCF Files</h3>
<p>VCF files can represent several types of genetic variation:</p>
<p><strong>SNVs (Single Nucleotide Variants)</strong>: Position 136 above shows a simple G→A substitution</p>
<p><strong>Indels</strong>:</p>
<ul>
<li><strong>Deletions</strong>: Position 457 shows a deletion where CA in the reference becomes C (one base deleted)</li>
<li><strong>Insertions</strong>: Can be represented as <code>A→ATAAATTTTTT</code> where bases are added</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Additional Indel Examples
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>chrI    17290   .       AACAC   A       80.01   .       AC=1;AF=1.00;AN=1;DP=4;MQ=36.85;QD=27.08;SOR=2.303  GT:AD:DP:GQ:PL  1:0,2:2:90:90,0
chrI    30097   .       A       ATAAATTTTTT     125.04  .       AC=1;AF=1.00;AN=1;DP=3;MQ=26.04;QD=21.53;SOR=1.179  GT:AD:DP:GQ:PL  1:0,3:3:99:135,0
chrI    31122   .       CATAT   C       69.01   .       AC=1;AF=1.00;AN=1;DP=6;MQ=60.00;QD=34.50;SOR=2.303  GT:AD:DP:GQ:PL  1:0,2:2:79:79,0</code></pre>
<ul>
<li>Position 17290: 4bp deletion (AACAC→A)</li>
<li>Position 30097: 10bp insertion (A→ATAAATTTTTT)</li>
<li>Position 31122: 4bp deletion (CATAT→C)</li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="bed-file-format-and-bedtools" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="bed-file-format-and-bedtools"><span class="header-section-number">3.8</span> BED file format and BEDtools</h2>
<p>The Browser Extensible Data (BED) format is a tab-delimited text format for storing genomic regions as coordinates and associated annotations. Originally developed during the Human Genome Project for the UCSC Genome Browser<span class="citation" data-cites="kent_human_2002"><sup><a href="#ref-kent_human_2002" role="doc-biblioref">13</a></sup></span>, BED has become a de facto standard in bioinformatics for representing genomic intervals.</p>
<p>The key advantage of BED format is its use of genomic coordinates rather than sequences, which optimizes computational efficiency when comparing genomic regions. Its simplicity also makes it easy to manipulate using standard command-line tools, scripting languages, or specialized utilities like BEDTools<span class="citation" data-cites="quinlan_bedtools_2010"><sup><a href="#ref-quinlan_bedtools_2010" role="doc-biblioref">14</a></sup></span>.</p>
<section id="bed-file-structure" class="level3" data-number="3.8.1">
<h3 data-number="3.8.1" class="anchored" data-anchor-id="bed-file-structure"><span class="header-section-number">3.8.1</span> BED File Structure</h3>
<p>A minimal BED file requires three tab-delimited fields:</p>
<div class="cell">
<div id="tbl-bed-fields" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bed-fields-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.3: Core BED format fields.
</figcaption>
<div aria-describedby="tbl-bed-fields-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Column</th>
<th style="text-align: left;">Description</th>
<th style="text-align: left;">Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">chrom</td>
<td style="text-align: left;">Chromosome name</td>
<td style="text-align: left;">chr1</td>
</tr>
<tr class="even">
<td style="text-align: left;">chromStart</td>
<td style="text-align: left;">Start position (0-based)</td>
<td style="text-align: left;">1000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">chromEnd</td>
<td style="text-align: left;">End position (1-based, exclusive)</td>
<td style="text-align: left;">1500</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Important</strong>: BED uses a 0-based coordinate system for the start position and a 1-based coordinate system for the end position. This means:</p>
<ul>
<li>The first nucleotide of a chromosome has <code>chromStart=0, chromEnd=1</code></li>
<li>A feature’s length is simply <code>chromEnd - chromStart</code></li>
<li>The position chr1:1001-1500 in “human” coordinates becomes <code>chr1 1000 1500</code> in BED format</li>
</ul>
<p>The BED format supports up to 12 standard fields, with the first three being mandatory:</p>
<div class="cell">
<div id="tbl-bed-extended" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bed-extended-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.4: Extended BED format fields (optional fields 4-12).
</figcaption>
<div aria-describedby="tbl-bed-extended-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Field</th>
<th style="text-align: left;">Name</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: left;">name</td>
<td style="text-align: left;">Feature name or identifier</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: left;">score</td>
<td style="text-align: left;">Score (0-1000)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: left;">strand</td>
<td style="text-align: left;">Strand: + or -</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: left;">thickStart</td>
<td style="text-align: left;">Start of thick drawing (e.g., coding region)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: left;">thickEnd</td>
<td style="text-align: left;">End of thick drawing</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: left;">itemRgb</td>
<td style="text-align: left;">RGB color value (e.g., 255,0,0)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: left;">blockCount</td>
<td style="text-align: left;">Number of blocks (exons)</td>
</tr>
<tr class="even">
<td style="text-align: right;">11</td>
<td style="text-align: left;">blockSizes</td>
<td style="text-align: left;">Comma-separated list of block sizes</td>
</tr>
<tr class="odd">
<td style="text-align: right;">12</td>
<td style="text-align: left;">blockStarts</td>
<td style="text-align: left;">Comma-separated list of block starts</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="example-bed-files" class="level3" data-number="3.8.2">
<h3 data-number="3.8.2" class="anchored" data-anchor-id="example-bed-files"><span class="header-section-number">3.8.2</span> Example BED Files</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Simple BED3 Format
</div>
</div>
<div class="callout-body-container callout-body">
<p>A basic three-column BED file showing genomic intervals:</p>
<pre><code>chr1    1000    1500
chr1    2000    2300
chr2    5000    5800
chrX    1000000 1001000</code></pre>
<p>This represents four genomic regions. The first spans 500 bp from position 1000 to 1499 on chromosome 1 (remember: end position is exclusive).</p>
</div>
</div>
</section>
<section id="working-with-bed-files-bedtools" class="level3" data-number="3.8.3">
<h3 data-number="3.8.3" class="anchored" data-anchor-id="working-with-bed-files-bedtools"><span class="header-section-number">3.8.3</span> Working with BED Files: BEDTools</h3>
<p>BEDTools<span class="citation" data-cites="quinlan_bedtools_2010"><sup><a href="#ref-quinlan_bedtools_2010" role="doc-biblioref">14</a></sup></span> is a powerful suite of utilities for performing “genome arithmetic” on BED files. These tools enable efficient comparison and manipulation of genomic features through set operations like intersect, merge, and complement. BEDTools can be combined with standard UNIX commands in pipelines, facilitating complex genomic analyses without requiring web-based tools or large data transfers.</p>
</section>
<section id="bed-format-in-other-tools" class="level3" data-number="3.8.4">
<h3 data-number="3.8.4" class="anchored" data-anchor-id="bed-format-in-other-tools"><span class="header-section-number">3.8.4</span> BED Format in Other Tools</h3>
<p>Beyond BEDTools, BED format is supported by numerous bioinformatics tools:</p>
<ul>
<li><strong>UCSC Genome Browser tools</strong>: bedToBigBed, bigBedToBed for creating indexed binary formats</li>
<li><strong>R/Bioconductor</strong>: <code>rtracklayer</code> for importing/exporting BED files, <code>GenomicRanges</code> for genomic interval operations</li>
<li><strong>Python</strong>: <code>pybedtools</code> provides Python interface to BEDTools functionality</li>
<li><strong>IGV (Integrative Genomics Viewer)</strong>: Native support for BED track display</li>
</ul>
</section>
<section id="connection-to-genome-browsers" class="level3" data-number="3.8.5">
<h3 data-number="3.8.5" class="anchored" data-anchor-id="connection-to-genome-browsers"><span class="header-section-number">3.8.5</span> Connection to Genome Browsers</h3>
<p>BED files serve as a fundamental format for displaying custom annotation tracks in genome browsers. The UCSC Genome Browser<span class="citation" data-cites="kent_human_2002"><sup><a href="#ref-kent_human_2002" role="doc-biblioref">13</a></sup></span> uses BED format extensively, allowing researchers to:</p>
<ol type="1">
<li><strong>Upload custom tracks</strong> for visualization alongside reference annotations</li>
<li><strong>Define track display properties</strong> through optional track lines</li>
<li><strong>Share results</strong> by hosting BED files on web servers</li>
</ol>
<p>For large datasets, BED files can be converted to <strong>bigBed</strong> format<span class="citation" data-cites="kent_bigwig_2010"><sup><a href="#ref-kent_bigwig_2010" role="doc-biblioref">15</a></sup></span>, a compressed, indexed binary format that enables rapid visualization of millions of features without uploading entire datasets to the browser.</p>
<p>As we transition to Chapter 4 on Genome Browsers, understanding BED format provides the foundation for effectively visualizing and interpreting genomic data. Genome browsers use BED-formatted tracks to display genes, regulatory elements, variants, and experimental results in their chromosomal context, making BED fluency essential for modern genomics research.</p>
<hr>
</section>
</section>
<section id="practice-problemsets" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="practice-problemsets"><span class="header-section-number">3.9</span> Practice Problem‑sets</h2>
<ol type="1">
<li><p>The chapter mentions that Q20 is a recommended cutoff for typical sequencing projects, but that this still equates to ~100 million errors in a standard sequencing project. This was based on a dataset with 100 million 100 base pair reads, or 10 billion reads. Imagine you increased the stringency from 99% to 99.9% by imposing a Q30 cutoff instead. <strong>What would be the new number of expected sequencing errors resulting from this adjustment?</strong></p></li>
<li><p>Quality control is the critical first step in any sequencing analysis. Different research environments (local computers, web platforms, command-line servers, R environments) offer different tools for QC analysis. To better understand the strengths and limitations of each approach, compare FastQC implementations across different platforms. To do this, search the SRA accession <strong>SRR518692</strong> (<em>Aeromonas hydrophila</em> whole genome sequencing) which was sequenced here at Auburn. In class, we will run FastQC using the Galaxy Web Platform. Here, test out a local FastQC Installation (Mac/Windows). First, download <a href="https://www.bioinformatics.babraham.ac.uk/projects/download.html#fastqc">FastQC</a> for Mac/PC. Next, download the SRR518692 FASTQ files using Galaxy or SRA Toolkit. Third, run FastQC locally on the downloaded file. <strong>Compare the output to your Galaxy results from class.</strong></p></li>
<li><p>As an extension of Problem #2, look up the genome size of the species <em>Aeromonas hydrophila</em> on NCBI. Then using the number of reads and the read length from the FastQC report, <strong>calculate the expected coverage</strong> of this sample.</p></li>
<li><p>As another example of tool implementation, try your hand at <strong>running FastQC using the R/Bioconductor Approach</strong>. There are several R pacakges that you can use. If you have installed FastQC, then you can use <a href="https://cran.r-project.org/web/packages/fastqcr/readme/README.html">fastqcr</a>. Alternatively, you can use an alternative pacakge called <a href="https://kasperdanielhansen.github.io/genbioconductor/html/ShortRead.html">ShortRead</a>. Once you have retrieved QC metrics using either R package, <em>compare your results with that of Galaxy and FastQC locally. Also reflect on the difference in experience across these three platforms. Which was easiest to run? fastest? Which was easiest to interpret? Which one would you choose if you needed to run these QC metrics on a set of 100 fastqc files?</em></p></li>
<li><p>Look back at the Lab from Computational Biology where you learned to use AWK to manipulate VCF files. Now having learned more about this file format, why do you think a VCF file worked so well for this lab assignment working with the tool <code>awk</code>?</p></li>
<li><p><strong>SAM/BAM CIGAR Strings</strong>: Alignment information encoded in SAM/BAM files use CIGAR strings. CIGAR (Compact Idiosyncratic Gapped Alignment Report) strings provide a compressed representation of how reads align to a reference genome. Given these CIGAR strings, decode what they mean: a). <code>148M2S</code> (from chapter example); b). <code>50M1I49M</code>; c). <code>75M5D25M</code>; d). <code>10S90M</code>. <em>Write out what they mean in plain English. How long is each read corresponding to each string? What types of potential variants do these reads indicate?</em></p></li>
</ol>
</section>
<section id="reflection-questions" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="reflection-questions"><span class="header-section-number">3.10</span> Reflection Questions</h2>
<ol type="1">
<li><p><strong>Format Evolution and Compression</strong>: The chapter describes the evolution from FASTA → FASTQ → SAM → BAM → CRAM, with each format adding information or improving compression. Explain the trade-offs between human readability and computational efficiency in this progression. Why do you think FASTA has remained the standard for reference genomes for 40 years despite being uncompressed text, while CRAM has largely replaced SAM/BAM for aligned reads?</p></li>
<li><p><strong>Phred Quality Score as ASCII</strong>: In the FastQ file format, Phred quality scores are encoded as ASCII (+33 offset) rather than raw numbers. Why do you think this format is preferred?</p></li>
<li><p><strong>Phred Quality Score Encoding</strong>: FASTQ format encodes Phred quality scores as single ASCII characters with a +33 offset (e.g., Q30 becomes ‘?’) rather than storing them as numeric values (e.g., “30”). Why do you think was this ASCII encoding scheme chosen? What benefits do you think this conversion has in terms of file compression? For example, why might the string “?????” (five Q30 scores) compress differently than “30,30,30,30,30”? Would ASCII encoding help or hurt compression? What are the trade-offs between human-readability and computational efficiency?</p></li>
<li><p><strong>Different ASCII encoding</strong>: The +33 offset specifically makes quality scores printable characters (! through ~). The earlier Solexa/Illumina 1.0 format used +64 offset (@ through ~). What practical problems might arise from having two different encoding schemes in the field? How would you detect which encoding a file uses?</p></li>
<li><p><strong>Coordinate Systems and Biological Meaning</strong>: BED format uses 0-based start positions but 1-based end positions (0-based, half-open intervals), while VCF uses 1-based positions for both start and end. Discuss why these different conventions exist and how they affect biological interpretation. What errors might occur if you incorrectly convert between these systems? Provide a specific example with coordinates.</p></li>
</ol>
</section>
<section id="references" class="level2" data-number="3.11">
<h2 data-number="3.11" class="anchored" data-anchor-id="references"><span class="header-section-number">3.11</span> References</h2>


<div id="refs" class="references csl-bib-body" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-pevsner2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Pevsner, J. <em>Bioinformatics and Functional Genomics</em>. (Wiley, 2015).</div>
</div>
<div id="ref-lipman_rapid_1985" class="csl-entry" role="listitem">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Lipman, D. J. &amp; Pearson, W. R. <a href="https://doi.org/10.1126/science.2983426">Rapid and sensitive protein similarity searches</a>. <em>Science</em> <strong>227</strong>, 1435–1441 (1985).</div>
</div>
<div id="ref-pearson_improved_1988" class="csl-entry" role="listitem">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Pearson, W. R. &amp; Lipman, D. J. <a href="https://doi.org/10.1073/pnas.85.8.2444">Improved tools for biological sequence comparison</a>. <em>Proceedings of the National Academy of Sciences</em> <strong>85</strong>, 2444–2448 (1988).</div>
</div>
<div id="ref-cock2010" class="csl-entry" role="listitem">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">Cock, P. J. A., Fields, C. J., Goto, N., Heuer, M. L. &amp; Rice, P. M. <a href="https://doi.org/10.1093/nar/gkp1137">The <span>Sanger</span> <span>FASTQ</span> file format for sequences with quality scores, and the <span>Solexa</span>/<span>Illumina</span> <span>FASTQ</span> variants</a>. <em>Nucleic Acids Research</em> <strong>38</strong>, 1767–1771 (2010).</div>
</div>
<div id="ref-fastqc" class="csl-entry" role="listitem">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">Institute, B. <a href="https://www.bioinformatics.babraham.ac.uk/projects/fastqc/">Babraham <span>Bioinformatics</span> - <span>FastQC</span> <span>A</span> <span>Quality</span> <span>Control</span> tool for <span>High</span> <span>Throughput</span> <span>Sequence</span> <span>Data</span></a>.</div>
</div>
<div id="ref-burke_standing_2014" class="csl-entry" role="listitem">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Burke, M. K., Liti, G. &amp; Long, A. D. <a href="https://doi.org/10.1093/molbev/msu256">Standing <span>Genetic</span> <span>Variation</span> <span>Drives</span> <span>Repeatable</span> <span>Experimental</span> <span>Evolution</span> in <span>Outcrossing</span> <span>Populations</span> of <span>Saccharomyces</span> cerevisiae</a>. <em>Molecular Biology and Evolution</em> <strong>31</strong>, 3228–3239 (2014).</div>
</div>
<div id="ref-Li2009SAMtools" class="csl-entry" role="listitem">
<div class="csl-left-margin">7. </div><div class="csl-right-inline"><span class="nocase">Li, H. <em>et al.</em></span> <a href="https://doi.org/10.1093/bioinformatics/btp352">The sequence alignment/map format and SAMtools</a>. <em>Bioinformatics</em> <strong>25</strong>, 2078–2079 (2009).</div>
</div>
<div id="ref-danecek_twelve_2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">8. </div><div class="csl-right-inline">Danecek, P. <em>et al.</em> <a href="https://doi.org/10.1093/gigascience/giab008">Twelve years of <span>SAMtools</span> and <span>BCFtools</span></a>. <em>GigaScience</em> <strong>10</strong>, giab008 (2021).</div>
</div>
<div id="ref-danecek_variant_2011" class="csl-entry" role="listitem">
<div class="csl-left-margin">9. </div><div class="csl-right-inline">Danecek, P. <em>et al.</em> <a href="https://doi.org/10.1093/bioinformatics/btr330">The variant call format and <span>VCFtools</span></a>. <em>Bioinformatics (Oxford, England)</em> <strong>27</strong>, 2156–2158 (2011).</div>
</div>
<div id="ref-learning_vcf" class="csl-entry" role="listitem">
<div class="csl-left-margin">10. </div><div class="csl-right-inline"><a href="https://davetang.github.io/learning_vcf_file/">Learning the <span>VCF</span> format</a>.</div>
</div>
<div id="ref-mckenna_genome_2010" class="csl-entry" role="listitem">
<div class="csl-left-margin">11. </div><div class="csl-right-inline">McKenna, A. <em>et al.</em> <a href="https://doi.org/10.1101/gr.107524.110">The <span>Genome</span> <span>Analysis</span> <span>Toolkit</span>: A <span>MapReduce</span> framework for analyzing next-generation <span>DNA</span> sequencing data</a>. <em>Genome Research</em> <strong>20</strong>, 1297–1303 (2010).</div>
</div>
<div id="ref-depristo_framework_2011" class="csl-entry" role="listitem">
<div class="csl-left-margin">12. </div><div class="csl-right-inline">DePristo, M. A. <em>et al.</em> <a href="https://doi.org/10.1038/ng.806">A framework for variation discovery and genotyping using next-generation <span>DNA</span> sequencing data</a>. <em>Nature Genetics</em> <strong>43</strong>, 491–498 (2011).</div>
</div>
<div id="ref-kent_human_2002" class="csl-entry" role="listitem">
<div class="csl-left-margin">13. </div><div class="csl-right-inline">Kent, W. J. <em>et al.</em> <a href="https://doi.org/10.1101/gr.229102">The human genome browser at <span>UCSC</span></a>. <em>Genome Research</em> <strong>12</strong>, 996–1006 (2002).</div>
</div>
<div id="ref-quinlan_bedtools_2010" class="csl-entry" role="listitem">
<div class="csl-left-margin">14. </div><div class="csl-right-inline">Quinlan, A. R. &amp; Hall, I. M. <a href="https://doi.org/10.1093/bioinformatics/btq033"><span>BEDTools</span>: A flexible suite of utilities for comparing genomic features</a>. <em>Bioinformatics</em> <strong>26</strong>, 841–842 (2010).</div>
</div>
<div id="ref-kent_bigwig_2010" class="csl-entry" role="listitem">
<div class="csl-left-margin">15. </div><div class="csl-right-inline">Kent, W. J., Zweig, A. S., Barber, G., Hinrichs, A. S. &amp; Karolchik, D. <a href="https://doi.org/10.1093/bioinformatics/btq351"><span>BigWig</span> and <span>BigBed</span>: Enabling browsing of large distributed datasets</a>. <em>Bioinformatics</em> <strong>26</strong>, 2204–2207 (2010).</div>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ch02-sequencing-tech.html" class="pagination-link" aria-label="Sequencing Technologies and Data Formats">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Sequencing Technologies and Data Formats</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ch04-browsers-databases.html" class="pagination-link" aria-label="Genome Databases and Browsers">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Genome Databases and Browsers</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>